---
- name: Configure Proxy Nodes (Keepalived + HAProxy)
  hosts: proxy
  become: yes
  tasks:
    - name: Update apt cache
      shell: apt-get update
      changed_when: false

    - name: Install Keepalived and HAProxy
      package:
        name:
          - keepalived
          - haproxy
        state: present

    # --- Настройка Keepalived ---
    - name: Configure Keepalived
      copy:
        dest: /etc/keepalived/keepalived.conf
        content: |
          vrrp_instance VI_1 {
              state {{ 'MASTER' if inventory_hostname == 'ha1-cod' else 'BACKUP' }}
              interface ens18
              virtual_router_id 51
              priority {{ 100 if inventory_hostname == 'ha1-cod' else 50 }}
              advert_int 1
              virtual_ipaddress {
                  172.16.1.253/23
              }
          }
      notify: Restart keepalived

    - name: Добавление dns-сервера
      ansible.builtin.lineinfile:
        path: /etc/net/ifaces/ens18/resolv.conf
        line: "nameserver 10.1.1.10"
        create: yes
        mode: '0644'

    # --- Настройка HAProxy ---
    - name: Ensure group "haproxy" exists
      ansible.builtin.group:
        name: haproxy
        state: present
        system: yes

    - name: Ensure user "haproxy" exists
      ansible.builtin.user:
        name: haproxy
        group: haproxy
        state: present
        system: yes
        shell: /bin/false
        create_home: no
        home: /var/lib/haproxy

    - name: Configure HAProxy
      ansible.builtin.template:
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: '0644'
        validate: 'haproxy -c -f %s'
        content: |
          global
              daemon
              user haproxy
              group haproxy
              chroot /var/lib/haproxy
              log /dev/log local0
              ssl-default-bind-ciphers PROFILE=SYSTEM

          defaults
              mode http
              log global
              option httplog
              timeout connect 5000ms
              timeout client 50000ms
              timeout server 50000ms

          frontend http_front
              bind 172.16.1.253:80
              http-request redirect scheme https code 301 unless { ssl_fc }

          frontend https_front
              bind 172.16.1.253:443 ssl crt /etc/haproxy/certs/www.au.team.crt
              option forwardfor
              http-request set-header X-Forwarded-Proto https
              default_backend web_servers

          backend web_servers
              balance roundrobin
              option httpchk GET /
              {% for host in groups['server'] %}
              server {{ host }} {{ host }}:80 check inter 2s rise 2 fall 3
              {% endfor %}

          listen stats
              bind 172.16.1.253:9000
              stats enable
              stats uri /haproxy_stats
              stats refresh 5s
      notify: Restart haproxy


    - name: Ensure services are started
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - keepalived
        - haproxy

  handlers:
    - name: Restart keepalived
      service:
        name: keepalived
        state: restarted

    - name: Restart haproxy
      service:
        name: haproxy
        state: restarted
