---
- name: Сбор информации и проверка сервисов
  hosts: all
  gather_facts: true
  vars:
    required_services:
      - pdns
      - pdns-recursor
      - dhcpd
      - dhcp-relay
      - nftables
      - rsyslog
      - chrony
  tasks:
    - name: Сбор фактов о сервисах
      ansible.builtin.service_facts:

    - name: Генерация итогового отчета на управляющем узле
      delegate_to: localhost
      run_once: true
      ansible.builtin.copy:
        dest: /etc/ansible/otchet
        content: |
          Имена устройств согласно списка
          {% for host in groups['all'] %}
          {{ hostvars[host]['inventory_hostname'] }} - {{ hostvars[host]['ansible_facts']['fqdn'] | default('localhost') }}
          {% endfor %}

          ##########

          Статусы сервисов
          {% for host in groups['all'] %}
          {% for service in required_services %}
          {% set s_name = service + '.service' %}
          {% if s_name in hostvars[host]['ansible_facts']['services'] %}
          {{ service }} на {{ host }} - статус `{{ hostvars[host]['ansible_facts']['services'][s_name]['state'] }} ({{ hostvars[host]['ansible_facts']['services'][s_name]['status'] }})`
          {% else %}
          {{ service }} на {{ host }} - статус `not-found`
          {% endif %}
          {% endfor %}
          {% endfor %}
        mode: '0644'

